---
title: "Report"
author: "David Keyes"
output: word_document
---

```{r setup, include=FALSE}
# This is the setup chunk
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)
```

```{r}
# Here we load packages
library(tidyverse)
```

# Import Data

```{r}
nhanes <- read_csv("data/nhanes.csv")
```

# Data Analysis

```{r}
nhanes %>% 
  count(education)
```


```{r}
physically_active_education <- nhanes %>% 
  group_by(education) %>% 
  summarize(days_active = mean(phys_active_days, na.rm = TRUE)) %>% 
  mutate(days_active = round(days_active, 1)) %>% 
  drop_na(education)

physically_active_education

```


# Data Visualization


## Basic Bar Chart

```{r}
ggplot(physically_active_education, aes(x = education,
                                        y = days_active)) +
  geom_col() + 
  coord_flip()
```

## Reordered Bar Chart

```{r}
ggplot(physically_active_education, aes(x = reorder(education, days_active),
                                        y = days_active)) +
  geom_col() + 
  coord_flip()
```

## Add Text

```{r}
ggplot(physically_active_education, aes(x = reorder(education, days_active),
                                        y = days_active)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() 
```

## Adjust Labels


```{r}
ggplot(physically_active_education, aes(x = reorder(education, days_active),
                                        y = days_active)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  labs(x = "",
       y = "Days Active")
```

## Add Color/Fill

```{r}
ggplot(physically_active_education, aes(x = reorder(education, days_active),
                                        y = days_active,
                                        fill = education)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "Days Active")
```





## Highlights


```{r}
library(gghighlight)

ggplot(physically_active_education, aes(x = reorder(education, days_active),
                                        y = days_active,
                                        fill = education)) +
  geom_col() + 
  gghighlight(days_active == 3.9) +
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "Days Active")
```


# Facets

```{r}
physically_active_gender_education <- nhanes %>% 
  group_by(gender, education) %>% 
  summarize(days_active = mean(phys_active_days, na.rm = TRUE)) %>% 
  mutate(days_active = round(days_active, 1)) %>% 
  drop_na(education)

```

```{r}
ggplot(physically_active_gender_education, aes(x = reorder(education, days_active),
                                               y = days_active,
                                               fill = gender)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "Days Active") +
  facet_wrap(~gender) 
```



# Themes

## BBC

```{r}
library(bbplot)

ggplot(physically_active_gender_education, aes(x = reorder(education, days_active),
                                               y = days_active,
                                               fill = gender)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "Days Active") +
  facet_wrap(~gender) +
  bbc_style()




```

## FiveThirtyEight
```{r}
library(ggthemes)

ggplot(physically_active_gender_education, aes(x = reorder(education, days_active),
                                               y = days_active,
                                               fill = gender)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "Days Active") +
  facet_wrap(~gender) +
  theme_fivethirtyeight()




```

## Urban Institute

```{r}
library(urbnthemes)

set_urbn_defaults()

ggplot(physically_active_gender_education, aes(x = reorder(education, days_active),
                                               y = days_active,
                                               fill = gender)) +
  geom_col() + 
  geom_text(aes(label = days_active),
            hjust = 1) +
  coord_flip() +
  theme(legend.position = "none") +
  labs(x = "",
       y = "Days Active") +
  facet_wrap(~gender)
  
```

